import type { Metadata } from "next";
import "../assests/style/app.scss"
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import { ReduxProvider } from "@/redux/Provider/ReduxProvider";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { CategoryProvider } from "@/components/main/Category/CategoryContext";
import DynamicTitle from "@/components/main/DynamicTitle/DynamicTitle";
config.autoAddCss = false


export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: "./favicon.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <DynamicTitle/>
        <ReduxProvider>
          <CategoryProvider>
            <Header />
            {children}
            <Footer />
            </CategoryProvider >
        </ReduxProvider>
      </body>
    </html>
  );
}
